spin_version = "1"
authors = ["chris <chris.matteson@gmail.com>"]
description = "An example app for the quickstart"
name = "example-app"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "example-app"
source = "target/wasm32-wasi/release/example_app.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
